# Generated by Django 4.2.3 on 2023-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_avatarmodel_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarmodel',
            name='avatar_id',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
