# Generated by Django 4.2.3 on 2023-09-14 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 14, 17, 52, 48, 475912, tzinfo=datetime.timezone.utc)),
        ),
    ]
