# Generated by Django 4.2.3 on 2023-09-15 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_date_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 15)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 15, 7, 35, 37, 614243, tzinfo=datetime.timezone.utc)),
        ),
    ]
