# Generated by Django 4.2.3 on 2023-09-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_date_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 19)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='09:32:25'),
        ),
    ]
