# Generated by Django 4.2.3 on 2023-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
