# Generated by Django 4.2.3 on 2023-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
