# Generated by Django 4.2.3 on 2023-09-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_alter_avatarmodel_avatar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('title', models.CharField(default='Update', max_length=50)),
                ('message', models.CharField(default='', max_length=1000)),
                ('image_or_video', models.CharField(default='', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
